import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";
import NextTopLoader from 'nextjs-toploader';
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tech Titans",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <ClerkProvider>
     <html lang="en">
      <body className={inter.className}>
        <Header />
        <NextTopLoader />
        {children}
        <Footer />
      </body>
    </html>
   </ClerkProvider>
  );
}
