import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";
import NextTopLoader from 'nextjs-toploader';
import MyComponent from './login/Login'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tech Titans",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  let isLogin = false;
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <NextTopLoader />
        {isLogin? <MyComponent/> :children}
        <Footer />
      </body>
    </html>
  );
}
